name: "Build and test"

on:
  push:
    branches: [ "tip-of-tree" ]
  pull_request:
    branches: [ "tip-of-tree" ]

permissions:
  contents: read

jobs:
  Validate:
    strategy:
      matrix:
        runner: [ubuntu-24.04]
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install check-jsonschema
      run: pip install check-jsonschema

    - name: Print check-jsonschema help
      run: check-jsonschema --help

    - name: Validate 6502.json with check-jsonschema
      run: check-jsonschema -v --builtin-schema InstructionSets/6502.json

    - name: Validate 6502 illegal.json with check-jsonschema
      run: check-jsonschema -v --schemafile InstructionSets/schema.json InstructionSets/6502\ illegal.json

    - name: Validate 8088 and 8086.json with check-jsonschema
      run: check-jsonschema -v --schemafile InstructionSets/schema.json InstructionSets/8088\ and\ 8086.json