name: "Build and test"

on:
  push:
    branches: [ "tip-of-tree" ]
  pull_request:
    branches: [ "tip-of-tree" ]

permissions:
  contents: read

jobs:
  Validate:
    strategy:
      matrix:
        runner: [ubuntu-24.04]
    runs-on: ${{ matrix.runner }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install check-jsonschema
      run: pip install check-jsonschema

    - name: Confirm InstructionSetSchema.json is a valid schema
      run: check-jsonschema -v --check-metaschema Schemas/InstructionSetSchema.json

    - name: Validate JSON files against schema
      run: check-jsonschema -v --schemafile Schemas/InstructionSetSchema.json InstructionSets/*.json